Don't play with fnmatch.c replacement
Currently fnmatch.c, even if it is selected, conditionally disables compilation
of fnmatch() funciton even though the rest of the code expects to get it (e.g.
because Autoconf didn't detect the working implementation and enabled fnmatch.c
to replace it). Drop the extra conditionals, to fix Autoconf magic.

Observed error:

ld: src/cabextract.o: in function `process_cabinet':
/usr/src/debug/cabextract/1.11/src/cabextract.c:499:(.text.startup+0xf1c): undefined reference to `rpl_fnmatch'
collect2: error: ld returned 1 exit status

Signed-off-by: Dmitry Baryshkov <dmitry.baryshkov@linaro.org>